import = [
  #"~/dotfiles/.config/alacritty/themes/noctis.toml" # light theme
  "~/dotfiles/.config/alacritty/themes/dracula.toml" # dark theme
]

[font]
size = 14

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"

[window]
opacity = 0.9
